### ISSUE TITLE
No response for Voice Commands

### ISSUE THREAD

**Issue by RahulChandrashekar17061984** [wiseman/ar-drone-rest#2]
Hi,

I tried to install all the dependencies and when i connect to the parrot drone wi-fi and execute the server.js

i get the below prompt ...but no response from the drone when i say "take-off"

D:\parrot_drone\ar-drone-rest-master>npm start

> ar-drone-rest@0.0.1 start D:\parrot_drone\ar-drone-rest-master
> node server.js

**ar-drone-rest listening at http://[::]:8080**

Am i missing something ?

**Comment by wiseman** [comment]
Yes, this code only provides a simple HTTP REST API to the drone, it does not handle voice commands.
